### ISSUE TITLE
Question: What does the color indicate?

### ISSUE THREAD

**Issue by mangatmodi** [plamenpasliev/BerlinHousing#1]
In the map, we have blue and red circles. What does the color and size of each indicate?

**Comment by plamenpasliev** [comment]
The color represents the price per sqm :) 

`cmap = matplotlib.cm.get_cmap('bwr')`

`norm = matplotlib.colors.Normalize(vmin=7, vmax=23)`

`color=col.to_hex(cmap(norm(row.PricePerSqm)))`

**Comment by mangatmodi** [comment]
Thanks man :)
Time to find my dream apartment...
